- README.md
- index.html
- package-lock.json
- package.json
- src/const.ts
- src/flash-log.ts
- src/flash-progress.ts
- src/flash.ts
- src/install-button.ts
- src/start-flash.ts
- src/util.ts
The log will be hidden by default now, but can be enabled with the `show-log` attribute.
The progress bar can be hidden with `hide-progress`
> Fire state changed events and add progess bar

- package-lock.json
- package.json
- src/flash.ts
- src/start-flash.ts
https://github.com/NabuCasa/ESP-Web-flasher/releases/tag/2.0.0
> Bump esp-web-flasher to 2.0 + hide improv button when done provision is done

- src/flash.ts
Tweak the text to make it easier to understand when to hold the button.
> Tweak failed init text

- index.html
Confirmed by Paulus that this is the official spelling.
> Correct spelling of "Wi-Fi"

- package-lock.json
- package.json
- src/flash.ts
Upgrade to ESP Web Tools and enable compression. This makes flashing a lot faster. 
https://github.com/NabuCasa/esp-web-flasher/releases/tag/3.1.0
https://github.com/NabuCasa/esp-web-flasher/releases/tag/3.1.1
> Upgrade to esp-web-flasher 3.1.1

- package-lock.json
- package.json
Improves logging to help debug #27 
https://github.com/NabuCasa/esp-web-flasher/releases/tag/3.1.2
> Upgrade esp web flasher to 3.1.2

- package-lock.json
- package.json
https://github.com/NabuCasa/esp-web-flasher/releases/tag/3.1.3
> Bump esp web flasher - fix ESP8266 support

- README.md
- src/const.ts
- src/flash.ts
- src/util.ts
Add support for the ESP32-C3. Also documents support for the ESP32-S2.
Fixes #37 
@conradopoole sorry for the delay 👍
> Add support for ESP32-C3

- src/start-flash.ts
Store state in the button instead of globals to allow multiple buttons on a page.
Fixes #52
> Store state on button

- package-lock.json
- package.json
Upgrade Material + Lit. 
Fixes #63
Fixes #67
> Upgrade material + Lit

- src/install-dialog.ts
Always offer the "provision device" button when the device was not provisioned.
Previously option was only offered during fresh install
Fixes #90
> Offer setup device if device was not provisioned

- src/components/ewt-console.ts
> Finish sending commands with \r\n

- src/install-dialog.ts
- Rename "Logs" to "Logs & Console"
- Show chip family
- Add icons in front of installed firmware + chip family
> Add icons and rename logs

- src/install-dialog.ts
Initially when the device wouldn't support improv we would throw them into the install step right away. The install step turned into a "light" version and would allow closing. Now that we offer "Logs & Console" option too, it simplifies the code to also offer a dashboard for non improv devices.
Before:
After:
> Split out non-improv dashboard from install dialog

- src/install-dialog.ts
Looks like I forgot to save a file 🙈 
CC @amandel
> Interpretet timeout in seconds, not ms

- src/components/ewt-console.ts
- src/install-dialog.ts
- src/util/console-color.ts
Align the console with the ESPHome implemenetation.
To do: test
> Align console with ESPHome

- package-lock.json
- package.json
Changelog https://github.com/NabuCasa/esp-web-flasher/releases/tag/5.0.0
Fixes https://github.com/esphome/esp-web-tools/issues/151
> Bump ESP Web Flasher to 5.0.0

- package.json
Hi!
I just noticed that the link to the repository was incorrect.
André
> Fix link to the repository in package.json

- src/components/ewt-console.ts
- src/install-dialog.ts
- src/util/console-color.ts
- src/util/file-download.ts
Allow downloading the logs.
Synced over from https://github.com/esphome/dashboard/pull/193
> Allow downloading logs

- src/components/ewt-list-item.ts
- src/components/ewt-select.ts
- src/install-dialog.ts
> Scan for SSIDs

- src/util/chip-family-name.ts
see #203 But this do not fix the issues with the S3. Still not working
> add missing S3

- package-lock.json
- package.json
https://github.com/NabuCasa/esp-web-flasher/releases/tag/5.1.1
CC @Jason2866
> Bump ESP Web Flasher 5.1.1

- index.html
- src/install-dialog.ts
realized the name could be better.
> Rename checkSameFirmwareVersion to checkSameFirmware

- package-lock.json
- package.json
- tsconfig.json
Also imports helpers from `tslib`.
> Update MWC to 0.26.1

- package-lock.json
- package.json
Fixes progress update beyond ~70%. https://github.com/NabuCasa/esp-web-flasher/releases/tag/5.1.3
> Bump ESP Web Flasher 5.1.3

- package-lock.json
- package.json
https://github.com/NabuCasa/esp-web-flasher/releases/tag/5.1.4
* Increased timeout to 16MB spiffs flash problem ([#127](https://github.com/NabuCasa/esp-web-flasher/pull/127)) @robdobsn
Fixes #245
> ESP Web Flasher 5.1.4

- package-lock.json
- src/no-port-picked/no-port-picked-dialog.ts
- Add CH9102
- Link to manufacturer website for drivers of CH341
> Update driver suggestions

- src/no-port-picked/no-port-picked-dialog.ts
I updated the URL of 1 driver. (no-port-dialog)
> Update SILabs URL

- src/flash.ts
- fixes https://github.com/esphome/esp-web-tools/issues/270
- depending on file systems build did work or not
> Fix casing of ESPLoader.js

- index.html
As per https://github.com/esphome/esp-web-tools/issues/288#issuecomment-1239057646 updating the documentation.
CC @TD-er @Jason2866
> Add note about merging files

- index.html
CONNECT button is not working on "Try a live demo" because manifest file can't be found.
> Fix new manifest location

- package-lock.json
- package.json
- src/flash.ts
Changelog https://github.com/espressif/esptool-js/releases/tag/v0.3.0
> Bump esptool-js to 0.3.0

- package-lock.json
- package.json
https://github.com/espressif/esptool-js/commit/04e337db44c5249016342b477a1827e6409fc31e
> Bump to esptool-js 0.3.2

- package-lock.json
- package.json
- rollup.config.mjs
Transform local assignments that are part of Material Web 1 away so it doesn't break unpkg.
> Transform local assignment

- package-lock.json
- package.json
Changelog https://github.com/espressif/esptool-js/releases/tag/v0.5.3
> Update esptool.js to 0.5.3

- index.html
- src/install-dialog.ts
The console.log version is now updated to be OHF
> Update more branding to be OHF

- src/install-dialog.ts
fund development and erase user data were missing icons.
> Fix missing icons

- index.html
> Updated documentation with info on generating manifests

- index.html
Allow setting URL via manifest on demo page.
> Allow setting manifest via URL
