esphome/esp-web-tools

src/install-button.ts
Warn first if web serial would not be allowed because the context is not secure before checking if web serial is possible.
If web serial is not allowed, it will also be detected as not supported.
=> Reverse guard for serial allowed

src/connect.ts
Add support back for specifying the `manifest` as a property agian. This got accidentally dropped. Fixes #91
=> Also fetch manifest property again

src/components/ewt-console.ts
- Allow copy/paste text in the console again
- Remove send button as it was not hooked up
=> Console updates

README.md, index.html, src/const.ts, src/install-dialog.ts, static/firmware_build/manifest.json
This adds support to specify the domain of the integration in the manifest that supports the firmware that is being installed (optional key `home_assistant_domain`). When available, besides offering to visit the device, it will also offer to add it to Home Assistant.
Installing a new device once connected:
Provisioned device:
=> Add support for Home Assistant domain in manifest

index.html, src/const.ts, src/install-dialog.ts, static/firmware_build/manifest.json
Introduce new `new_install_skip_erase` option to manifests. Set to `true` to skip erasing all flash when doing a fresh install.
Fixes #100
=> Allow skipping erasing on new installations

package-lock.json, package.json
Fixes checksum calculations
Release notes: https://github.com/improv-wifi/sdk-serial-js/releases/tag/1.0.1
=> Bump improv-serial-sdk

src/install-dialog.ts
When both the firmware and the version are the same, allow users to clear the data. This will do a full erase + re-install of the firmware.
Same firmware + same version:
Same firmware, different version:
Different firmware:
CC @Aircoookie
=> Allow resetting data when firmware and version are the same

src/components/ewt-button.ts
Override the `min-width` on `<mdc-button>` and change it from `64px` to `initial`. It was causing buttons with short texts to be unaligned with the other buttons.
Before:
After:
=> Remove min width from button

src/install-dialog.ts
- Prevent body text alignment to leak into our dialog
- During installation, change header to `Installing <firmware>` instead of `Install <firmware>`
=> Install header + text align

src/connect.ts
`await navigator.serial.requestPort()` will raise not just when the user clicks "cancel", on Widnows it can also raise when the serial port is already in use.
Fixes #113
=> Do not silently ignore errors not caused by user closing picker

package-lock.json, package.json, src/install-dialog.ts
A firmware might take longer to boot when doing erase + install. For WLED we see times up to 6.5 seconds. This PR will allow Improv detection to take up to 10 seconds instead of the 1s default when flash was erased.
This PR also changes the screen when writing is done and we're trying to detect Improv. Previously we would show the "Installation complete" dialog and the button would enable when Improv was booted. This is not a good experience with a 10s wait, so instead we will now stay on the "Installing" screen and show "Wrapping up" while detecting Improv.
https://user-images.githubusercontent.com/1444314/141927851-2bfee325-706a-4b5b-a26c-ce158a56cdab.mp4
=> Wait longer for Improv to respond after erase + install

src/install-dialog.ts
The manifest option to skip fully erasing new installations was broken. This PR fixes it.
Fixes #126
=> Fix skip erase

src/install-button.ts
Pressing the ESP Web Tools button no longer starts the installation but offers users multiple options. To avoid user confusion the default label has been updated to say "CONNECT" instead of "INSTALL".
Before:
After:
=> Change default button label to "CONNECT"

index.html, src/const.ts, src/install-dialog.ts
Add support for a new `new_install_improv_wait_time` that allow you to specify the time ESP Web Tools should wait for an Improv Serial response after installing the firmware (default is 10 seconds). Set to 0 to disable waiting for Improv. 
@amandel can you verify that this build would solve your problems? 
Fixes #135
=> Allow configuring improv timeout

src/install-dialog.ts
This changes from displaying the OK_ICON to displaying the ERROR_ICON when FlashStateType is ERROR.
This should fix #161
=> Change from OK_ICON to ERROR_ICON when flash fails

src/install-dialog.ts
When ESP Web Tools represents the same project + firmware version that is already installed on the device, it will now offer the user to "Erase User Data" instead of the more confusing "Reset Data".
=> Update text: reset data -> erase user data

src/install-dialog.ts
Stop initialization when an error occurs.
#185 shows that the initialization continues when an error occurs. This pr fixes that.
=> Stop execution on error during initialization

src/connect.ts, src/install-dialog.ts, src/no-port-picked/index.ts, src/no-port-picked/no-port-picked-dialog.ts, src/styles.ts
Feature adopted from [ESPHome Web](https://web.esphome.io): if a user opens the webserial dialog but doesn't pick a device, help them troubleshoot.
=> Offer troubleshooting if no port selected

README.md, index.html, package.json, src/const.ts
Adds support for ESP32-S3.
https://github.com/NabuCasa/esp-web-flasher/releases/tag/5.1.0
CC @Jason2866
=> Bump ESP Web Flasher to 5.10

src/install-dialog.ts
Fixes showing "error 2" when the firmware didn't support listing SSIDs in Improv.
=> Improv: handle no SSID list support

index.html, src/connect.ts, src/install-button.ts, src/install-dialog.ts
Tasmota has special requirements for checking if a firmware is the same. Instead of trying to implement every case a firmware has for checking if it's the same firmware, this PR allows providing your own check firmware function. The function will be provided with the manifest and the information received via Improv. 
```js
const button = document.querySelector('esp-web-install-button');
button.overrides = {
checkSameFirmwareVersion(manifest, improvInfo) {
const manifestFirmware = manifest.name.toLowerCase();
const deviceFirmware = improvInfo.firmware.toLowerCase();
return manifestFirmware.includes(deviceFirmware);
}
};
```
Fixes #215
=> Allow specifying checkFirmware override

src/components/ewt-select.ts, src/components/ewt-textfield.ts, src/styles.ts
Noticed on Tasmota installation page that a bad REM can still impact form fields to look bigger than they should be.
Before:
After:
=> Make input select/textfield work better when bad REM defined

src/components/ewt-button.ts, src/install-dialog.ts
- Avoid long firmware names to be center aligned on buttons on the main device dashboard. This still is not ideal but it's an improvement.
- Rewrite the device info table using flex instead of table for better alignment
- Remove the manifest name from the heading during installation as we can't control the length and multi-line looks ugly.
=> better handle long firmware names

package-lock.json, package.json
Bump ESPTool to https://github.com/espressif/esptool-js/commit/076af269f44daa5b7823031221f39bf22124c129 to pull in latest C3 fixes.
=> Bump esptool.js

src/util/console-color.ts
Test if we scrolled to the bottom of the console before adding a new line. This fixes the bug where a new line that would wrap to 2+ lines would break the auto-scroll at the bottom.
=> Fix console not staying at bottom if new line spanned two lines

src/connect.ts, src/install-button.ts
Load the dialog while picking the port, not before showing the port picking dialog.
=> Code split smarter to get port picking done first

index.html
This updates the docs to automatically use the latest ESP Web Tools. Looks like unpkg with `?type=module` now works correctly.
=> Update the docs to automatically use latest ESP Web Tools

index.html
Partial backtracking of #321 and still recommend users to pin it to the v9 series.
=> Actually still recommend users 9

index.html
Remove en-us from the documentation URLs
=> Remove en-us from URLs

src/install-dialog.ts
When a device has just been installed/restarted, it can take some time to return results for Wi-Fi networks. This PR changes the behavior to automatically retry scanning for networks up to 2 times if no results are returned.
=> Retry fetching Wi-Fi SSIDs if no results post-install

src/components/ewt-console.ts, src/flash.ts
Taking one last stab with this approach, using slightly longer timings based on code I found [here](https://github.com/espressif/esptool/blob/590c2c68381b32e1d296d0b338b9d50a231169a5/esptool/reset.py#L126-L131).
=> Add small delay when resetting because USB JTAG, take 2

package-lock.json, package.json, rollup.config.mjs
Some of the Material Web components use JavaScript syntax that didn't get compiled, which broke unpkg. Unpkg is what we have always suggested as CDN to use for integrating ESP Web Tools on websites.
I put #475 in place to fix that. However, this can cause another breakage if another modern syntax slips in. To avoid this, this PR adds @babel/preset-env and targets Chrome 84.
Chrome 84 is the last version to not [support local assignment](https://caniuse.com/mdn-javascript_operators_logical_and_assignment).
We don't know the exact max version of Chrome that unpkg supports, but this should be a good safe first version.
=> Switch to preset-env for babel

src/components/ewt-console.ts, src/util/timestamp-transformer.ts
This creates `TimestampTransformer` which processes the incoming chunks (lines) and prepends a timestamp of the form `[HH:MM:SS]`
=> Create TimestampTransformer and use it in EwtConsole

src/flash.ts
Use the reset method on `ESPLoader`.
=> Migrate to native reset when available

index.html, static/logos/nspanelmanager.svg
Dear esp-web-tools maintainers, thanks for making the esp-web-tools, it definitely improved the user experience of our end users in the project NSPanel Manager: https://nspanelmanager.com/
We added a link and credit to esp-web-tools in the flashing page: https://nspanelmanager.com/flashing-tool.html `Installer powered by ESP Web Tools.`
Would be awesome if you would also accept to add the NSPanel Manager logo to the list of products using esp-web-tools 👍
=> Add nspanelmanager project to list

src/connect.ts, src/install-dialog.ts, src/util/console-color.ts, src/util/line-break-transformer.ts
- fix line breaks, look for both \r\n and \n
- increase buffer size for serial from 255 to 8192
- fix performance issues in the log console which caused delayed logging or the page to become unresponsive
- resolves https://github.com/esphome/esp-web-tools/issues/448
- resolves https://github.com/esphome/esp-web-tools/issues/545
=> Performance improvements + line break fix
